// <auto-generated />
using JobPortalCore.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobPortalCore.DAL.Migrations
{
    [DbContext(typeof(JobDbContext))]
    [Migration("20220204153159_CandidateRegister")]
    partial class CandidateRegister
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobPortalCore.Entity.Models.CandidateRegister", b =>
                {
                    b.Property<string>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MobNumber")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmailId");

                    b.ToTable("candidateRegister");
                });

            modelBuilder.Entity("JobPortalCoreApi.Entity.Models.JobDetails", b =>
                {
                    b.Property<int>("jobid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("companyname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("contactnumber")
                        .HasColumnType("int");

                    b.Property<string>("contactperson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("joblocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qualifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("technicalskills")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("jobid");

                    b.ToTable("job");
                });
#pragma warning restore 612, 618
        }
    }
}
